### ISSUE TITLE
Possibility to disable the notifications

### ISSUE THREAD

**Issue by idkwhatido** [Blacksuan19/plasma-wallpaper-wallhaven-reborn#7]
Hi,

thank you for porting the plugin and add the new features, i really love it.
There is only one thing that make me insane: i have multiple monitors and a relatively short change interval, so i get spammed with a notification every time the wallpaper change on one of my monitors.

Can you please say me how i can disable them?
I already tried the different notification-types and checked the applications, but not one of them worked.

Thank you very much in advance :)

**Comment by Blacksuan19** [comment]
Not possible at the moment.

**Comment by Blacksuan19** [comment]
implemented in latest commit!
